### ISSUE TITLE
Box need header !

### ISSUE THREAD

**Issue by LeDistordu** [sjlevine/dokuwiki-alertbox#1]
Alert box need header for clarity like this examples : 

![2015-05-31 22_19_07-les listes de controles d acces documentation centreon 2 6 1](https://cloud.githubusercontent.com/assets/7805145/7903645/378b205a-07e3-11e5-879f-0a6116e9057e.jpg)
![2015-05-31 22_18_36-a partir de ces documentation centreon 2 6 1](https://cloud.githubusercontent.com/assets/7805145/7903646/38d325f2-07e3-11e5-9ea3-c1a528e24249.jpg)

**Comment by sjlevine** [comment]
I prefer to keep this package as generating the traditional, Bootstrap-style alert messages shown here:
http://getbootstrap.com/components/#alerts

That being said, the titles could be useful. Feel free to create your own fork of this project and make the changes.
